### ISSUE TITLE
Rack::Flash causing errors - change to Sinatra::Flash

### ISSUE THREAD

**Issue by marielfrank** [learn-co-curriculum/playlister-sinatra#60] opened 2017-09-17 14:17 UTC
Rack::Flash was causing the following error on this lab:

`/home/marielfrank/playlister-sinatra-v-000/app/controllers/application_controller.rb:7:in '<class:ApplicationController>': uninitialized constant Rack::Flash (NameError)`

Switching to [Sinatra::Flash](https://github.com/SFEley/sinatra-flash), the issues were quickly resolved.

For the ERB,, it would be necessary to change this code:
`<% if flash.has?(:message) %>
  <%= flash[:message] %>
<% end %>`

to:

`<% if !!flash[:message] %>
  <%= flash[:message] %>
<% end %>`

**Comment by DakotaLMartinez** [comment] 2017-10-26 17:14
@gj this works for me. I've had a lot of students have issues with rack flash in Sinatra. And, a lot that don't... This seems like it could be a good alternative, though.

**Comment by ThePeej** [comment] 2018-02-08 20:18
Was running into the same issue, and this helped. However, I also was having trouble writing to the flash hash. I looked through the Sinatra Flash documentation a bit, and I eventually got it to work using the 'flash.next' hash.

So, just to clarify, in the post '/songs' & patch '/songs/:slug' routes, i used the following code

`flash.next[:message] = "Successfully updated song."`

This worked, and I still kept the songs/show.erb file the same as the suggestion above (still using flash[:message] as opposed to having to use flash.now[:message] or flash.next[:message])

**Comment by DanielSeehausen** [comment] 2018-03-13 15:26
Hi all -- thank you for bringing this to our attention. After following the readme (specifically the portion on `rack-flash3`, I was unable to reproduce the issue with the following code in the solution branch:
`
<% if flash.has?(:message) %>
  <%= flash[:message] %>
<% end %>
`

I'm having difficulty reproducing the issue, so I'm going to close it for now.


If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed by DanielSeehausen** 2018-03-13 15:26 UTC
Labels: Product
